stages:
  - build
  - deploy

variables:
  APP_REGISTRY: fe_blockademy
  APP_TAG_COMMIT: $APPSCYCLONE_REGISTRY/$APP_REGISTRY:$CI_COMMIT_SHORT_SHA

build_docker_dev: &build
  stage: build
  image: docker:23.0-cli
  services:
    - docker:dind
  variables:
    env: $ENV_DEV
    APP_TAG_LATEST: $APPSCYCLONE_REGISTRY/$APP_REGISTRY:beta-latest
  only:
    - develop
    - devops/k8s
  script:
    - cat $env > .env
    - docker login -u $DOCKER_USER -p $DOCKER_PASS $APPSCYCLONE_REGISTRY
    - docker build -t $APP_TAG_LATEST -t $APP_TAG_COMMIT .
    - docker push $APP_TAG_LATEST
    - docker push $APP_TAG_COMMIT
    - docker rmi -f $APP_TAG_LATEST $APP_TAG_COMMIT

build_docker_prod:
  <<: *build
  variables:
    env: $ENV_PROD
    APP_TAG_LATEST: $APPSCYCLONE_REGISTRY/$APP_REGISTRY:latest
  only:
    - master

deploy_beta: &deploy
  stage: deploy
  variables:
    NAMESPACE: blockademy-beta
  only:
    - develop
  image:
    name: alpine/k8s:1.25.16
    entrypoint: ['']
  before_script:
    - aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME --role-arn arn:aws:iam::604313529175:role/EksRoleBlockademy
  script:
    - kubectl rollout restart -n $NAMESPACE deploy blockademy-web

deploy_prod:
  <<: *deploy
  variables:
    NAMESPACE: blockademy-prod
  only:
    - master

