import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/redux/provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageContainer from "@/components/PageContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <PageContainer>
            <Header />
            {children}
            <Footer />
          </PageContainer>
        </Providers>
      </body>
    </html>
  );
}
